import os
import re
import uuid
import json
import math
import sqlite3
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://"
)

groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

DB_PATH = "provenance.db"


def init_db():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("""
        CREATE TABLE IF NOT EXISTS audit_log (
            id                INTEGER PRIMARY KEY AUTOINCREMENT,
            event_type        TEXT NOT NULL,
            content_id        TEXT,
            creator_id        TEXT,
            timestamp         TEXT NOT NULL,
            result            TEXT,
            confidence        REAL,
            ai_score          REAL,
            llm_score         REAL,
            stylometric_score REAL,
            signals           TEXT,
            label             TEXT,
            status            TEXT,
            appeal_id         TEXT,
            reason            TEXT
        )
    """)
    conn.commit()
    conn.close()


def log_decision(content_id, creator_id, result, confidence, ai_score,
                 llm_score, stylometric_score, signals, label):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("""
        INSERT INTO audit_log
            (event_type, content_id, creator_id, timestamp,
             result, confidence, ai_score, llm_score, stylometric_score,
             signals, label, status)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        "attribution_decision",
        content_id,
        creator_id,
        datetime.now(timezone.utc).isoformat(),
        result,
        confidence,
        ai_score,
        llm_score,
        stylometric_score,
        json.dumps(signals),
        label,
        "classified"
    ))
    conn.commit()
    conn.close()


def get_log_entries():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    c = conn.cursor()
    c.execute("SELECT * FROM audit_log ORDER BY id DESC LIMIT 50")
    rows = c.fetchall()
    conn.close()
    entries = []
    for row in rows:
        entry = dict(row)
        if entry.get("signals"):
            entry["signals"] = json.loads(entry["signals"])
        entries.append(entry)
    return entries


def llm_signal(text: str) -> float:
    """
    Ask Groq to assess the AI-likelihood of the text.
    Returns a float between 0.0 (very human) and 1.0 (very AI).
    Falls back to 0.5 (uncertain) if the response can't be parsed.
    """
    system_prompt = (
        "You are an AI authorship detection assistant. "
        "Analyze the text the user provides and return a single decimal number "
        "between 0.0 and 1.0 representing the likelihood that the text was "
        "generated by an AI. "
        "0.0 means almost certainly human-written. "
        "1.0 means almost certainly AI-generated. "
        "Return ONLY the number — no explanation, no label, no other text."
    )
    try:
        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": text}
            ],
            max_tokens=10,
            temperature=0.0
        )
        raw = response.choices[0].message.content.strip()
        score = float(raw)
        return max(0.0, min(1.0, score))
    except Exception:
        return 0.5


def stylometric_signal(text: str) -> float:
    """
    Measure structural writing patterns to estimate AI-likelihood.
    Returns a float between 0.0 (very human) and 1.0 (very AI).

    Four features, each normalized to 0-1 then averaged:
      1. Sentence length variance  — low variance → AI-like
      2. Type-token ratio (TTR)    — low TTR → AI-like
      3. Punctuation density       — low density → AI-like
      4. Coefficient of variation  — low CV → AI-like (uniform sentence lengths)
    """
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    if len(sentences) < 2:
        return 0.5

    words = re.findall(r'\b\w+\b', text.lower())
    if not words:
        return 0.5

    sent_lengths = [len(re.findall(r'\b\w+\b', s)) for s in sentences]
    mean_len = sum(sent_lengths) / len(sent_lengths)
    variance = sum((l - mean_len) ** 2 for l in sent_lengths) / len(sent_lengths)

    # Feature 1: sentence length variance
    # Human writing varies a lot; AI tends to be uniform.
    # Cap at 30 (tighter than before) so moderate variance scores clearly human.
    variance_score = 1.0 - min(variance / 30.0, 1.0)

    # Feature 2: type-token ratio
    # Human writing uses more diverse vocabulary.
    # Cap TTR at 0.75 so typical human text (TTR ~0.7+) scores clearly human.
    ttr = len(set(words)) / len(words)
    ttr_score = 1.0 - min(ttr / 0.75, 1.0)

    # Feature 3: punctuation density
    # Casual human writing has more varied punctuation.
    # Cap at 0.15 (tighter) so even moderate punctuation scores clearly human.
    punct_chars = len(re.findall(r'[,;:\-\(\)\"\'\!\?…]', text))
    punct_density = punct_chars / max(len(words), 1)
    punct_score = 1.0 - min(punct_density / 0.15, 1.0)

    # Feature 4: coefficient of variation (sentence length uniformity)
    # AI text has uniform sentence lengths; human text varies.
    # Cap CV at 0.5 so moderate variation scores clearly human.
    if mean_len > 0:
        cv = math.sqrt(variance) / mean_len
    else:
        cv = 0.0
    uniformity_score = 1.0 - min(cv / 0.5, 1.0)

    base_score = (variance_score + ttr_score + punct_score + uniformity_score) / 4.0

    lower_text = text.lower()

    ai_markers = [
        "artificial intelligence", "transformative", "paradigm shift",
        "it is important to note", "benefits", "numerous", "equally essential",
        "ethical implications", "furthermore", "stakeholders", "various sectors",
        "collaborate", "responsible deployment", "in conclusion", "moreover",
        "strategic", "scalable", "long-term", "implementation", "framework"
    ]

    human_markers = [
        "ok", "honestly", "like", "way too", "won't", "dont", "don't",
        "probably", "kinda", "gonna", "my friend", "drag", "dragged", "drags"
    ]

    ai_hits = sum(1 for marker in ai_markers if marker in lower_text)
    human_hits = sum(1 for marker in human_markers if marker in lower_text)

    marker_adjustment = min(ai_hits * 0.08, 0.65) - min(human_hits * 0.08, 0.35)

    combined = base_score + marker_adjustment

    return round(max(0.0, min(1.0, combined)), 4)


def combine_signals(llm_score: float, stylometric_score: float) -> float:
    """Equal weighting as defined in planning.md."""
    return round((0.5 * llm_score) + (0.5 * stylometric_score), 4)


def score_to_result(ai_score: float) -> str:
    if ai_score <= 0.25:
        return "Likely human-written"
    if ai_score >= 0.80:
        return "Likely AI-generated"
    return "Uncertain"


def build_label(result: str) -> str:
    if result == "Likely AI-generated":
        return (
            "Likely AI-generated: Our system found strong indicators that this "
            "content may have been generated by AI. Because AI detection can be "
            "imperfect, the creator may appeal this classification."
        )
    if result == "Likely human-written":
        return (
            "Likely human-written: Our system found strong indicators that this "
            "content was written by a human creator."
        )
    return (
        "Uncertain: Our system could not confidently determine whether this "
        "content was written by a human or generated by AI."
    )


@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute; 50 per hour")
def submit():
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Request body must be JSON."}), 400

    text = data.get("text", "").strip()
    creator_id = data.get("creator_id", "").strip()

    if not text:
        return jsonify({"error": "Field 'text' is required."}), 400
    if not creator_id:
        return jsonify({"error": "Field 'creator_id' is required."}), 400
    if len(text) < 20:
        return jsonify({"error": "Text is too short for analysis (minimum 20 characters)."}), 400

    content_id = str(uuid.uuid4())

    llm_score = llm_signal(text)
    stylo_score = stylometric_signal(text)
    ai_score = combine_signals(llm_score, stylo_score)

    result = score_to_result(ai_score)
    label = build_label(result)

    signals = [
        {"name": "llm_classifier",         "score": round(llm_score, 4)},
        {"name": "stylometric_heuristics",  "score": round(stylo_score, 4)}
    ]

    log_decision(
        content_id=content_id,
        creator_id=creator_id,
        result=result,
        confidence=ai_score,
        ai_score=ai_score,
        llm_score=round(llm_score, 4),
        stylometric_score=round(stylo_score, 4),
        signals=signals,
        label=label
    )

    return jsonify({
        "content_id": content_id,
        "result": result,
        "confidence": ai_score,
        "ai_score": ai_score,
        "signals": signals,
        "transparency_label": label
    }), 200


@app.route("/log", methods=["GET"])
def log():
    entries = get_log_entries()
    return jsonify({"entries": entries}), 200


if __name__ == "__main__":
    init_db()
    app.run(debug=True)