import os
import uuid
import json
import sqlite3
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://"
)

groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

DB_PATH = "provenance.db"


def init_db():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("""
        CREATE TABLE IF NOT EXISTS audit_log (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            event_type  TEXT NOT NULL,
            content_id  TEXT,
            creator_id  TEXT,
            timestamp   TEXT NOT NULL,
            result      TEXT,
            confidence  REAL,
            ai_score    REAL,
            llm_score   REAL,
            signals     TEXT,
            label       TEXT,
            status      TEXT,
            appeal_id   TEXT,
            reason      TEXT
        )
    """)
    conn.commit()
    conn.close()


def log_decision(content_id, creator_id, result, confidence, ai_score,
                 llm_score, signals, label):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("""
        INSERT INTO audit_log
            (event_type, content_id, creator_id, timestamp,
             result, confidence, ai_score, llm_score, signals, label, status)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        "attribution_decision",
        content_id,
        creator_id,
        datetime.now(timezone.utc).isoformat(),
        result,
        confidence,
        ai_score,
        llm_score,
        json.dumps(signals),
        label,
        "classified"
    ))
    conn.commit()
    conn.close()


def get_log_entries():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    c = conn.cursor()
    c.execute("SELECT * FROM audit_log ORDER BY id DESC LIMIT 50")
    rows = c.fetchall()
    conn.close()
    entries = []
    for row in rows:
        entry = dict(row)
        if entry.get("signals"):
            entry["signals"] = json.loads(entry["signals"])
        entries.append(entry)
    return entries


def llm_signal(text: str) -> float:
    """
    Ask Groq to assess the AI-likelihood of the text.
    Returns a float between 0.0 (very human) and 1.0 (very AI).
    Falls back to 0.5 (uncertain) if the response can't be parsed.
    """
    system_prompt = (
        "You are an AI authorship detection assistant. "
        "Analyze the text the user provides and return a single decimal number "
        "between 0.0 and 1.0 representing the likelihood that the text was "
        "generated by an AI. "
        "0.0 means almost certainly human-written. "
        "1.0 means almost certainly AI-generated. "
        "Return ONLY the number — no explanation, no label, no other text."
    )
    try:
        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": text}
            ],
            max_tokens=10,
            temperature=0.0
        )
        raw = response.choices[0].message.content.strip()
        score = float(raw)
        return max(0.0, min(1.0, score))
    except Exception:
        return 0.5


def build_label(result: str) -> str:
    if result == "Likely AI-generated":
        return (
            "Likely AI-generated: Our system found strong indicators that this "
            "content may have been generated by AI. Because AI detection can be "
            "imperfect, the creator may appeal this classification."
        )
    if result == "Likely human-written":
        return (
            "Likely human-written: Our system found strong indicators that this "
            "content was written by a human creator."
        )
    return (
        "Uncertain: Our system could not confidently determine whether this "
        "content was written by a human or generated by AI."
    )


def score_to_result(ai_score: float) -> str:
    if ai_score <= 0.25:
        return "Likely human-written"
    if ai_score >= 0.80:
        return "Likely AI-generated"
    return "Uncertain"


@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute; 50 per hour")
def submit():
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Request body must be JSON."}), 400

    text = data.get("text", "").strip()
    creator_id = data.get("creator_id", "").strip()

    if not text:
        return jsonify({"error": "Field 'text' is required."}), 400
    if not creator_id:
        return jsonify({"error": "Field 'creator_id' is required."}), 400
    if len(text) < 20:
        return jsonify({"error": "Text is too short for analysis (minimum 20 characters)."}), 400

    content_id = str(uuid.uuid4())

    llm_score = llm_signal(text)

    ai_score = llm_score
    confidence = ai_score
    result = score_to_result(ai_score)
    label = build_label(result)

    signals = [
        {"name": "llm_classifier", "score": round(llm_score, 4)}
    ]

    log_decision(
        content_id=content_id,
        creator_id=creator_id,
        result=result,
        confidence=round(confidence, 4),
        ai_score=round(ai_score, 4),
        llm_score=round(llm_score, 4),
        signals=signals,
        label=label
    )

    return jsonify({
        "content_id": content_id,
        "result": result,
        "confidence": round(confidence, 4),
        "ai_score": round(ai_score, 4),
        "signals": signals,
        "transparency_label": label
    }), 200


@app.route("/log", methods=["GET"])
def log():
    entries = get_log_entries()
    return jsonify({"entries": entries}), 200


if __name__ == "__main__":
    init_db()
    app.run(debug=True)
